name: Run Thirdweb Admin Script

on:
  workflow_dispatch: # Manual trigger

jobs:
  run-admin-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run transfer-ownership script
        env:
          THIRDWEB_SECRET_KEY: ${{ secrets.THIRDWEB_SECRET_KEY }}
          ENGINE_SERVER_WALLET_ADDRESS: ${{ secrets.ENGINE_SERVER_WALLET_ADDRESS }}
          ENGINE_VAULT_ACCESS_TOKEN: ${{ secrets.ENGINE_VAULT_ACCESS_TOKEN }}
          NEXT_PUBLIC_NFT_CONTRACT_ADDRESS: ${{ secrets.NEXT_PUBLIC_NFT_CONTRACT_ADDRESS }}
          NEW_OWNER_ADDRESS: ${{ secrets.NEW_OWNER_ADDRESS }}
          NEXT_PUBLIC_TOWNS_CONTRACT_ADDRESS: ${{ secrets.NEXT_PUBLIC_TOWNS_CONTRACT_ADDRESS }}
          TREASURY_TRANSFER_AMOUNT: ${{ secrets.TREASURY_TRANSFER_AMOUNT }}
          TREASURY_RECIPIENT_ADDRESS: ${{ secrets.TREASURY_RECIPIENT_ADDRESS }}
          TREASURY_ETH_TRANSFER_AMOUNT: ${{ secrets.TREASURY_ETH_TRANSFER_AMOUNT }}
        run: npx tsx scripts/transfer-ownership.ts
